version: '3'

services:
  redis:
    image: redis
  web:
    build: .
    command: gunicorn lastfm_django.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL="${REDIS_URL}"
